name: phaidra-s3

networks:
  phaidra-network:
    ipam:
      config:
        - subnet: 172.29.0.0/16
          ip_range: 172.29.7.0/24
          gateway: 172.29.5.1

services:
  httpd:
    image: httpd:2.4.59-bookworm
    pull_policy: always
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - "${PHAIDRA_HOSTPORT:-8899}:80"
    volumes:
      - .././container_init/httpd/phaidra-demo:/mnt/startup:ro
      - chronos-sitemaps:/mnt/sitemaps:ro
    depends_on:
      - api
      - ui
      - dbgate
      - solr
      - grafana
    networks:
      - phaidra-network
    environment:
      PHAIDRA_HOSTNAME: "${PHAIDRA_HOSTNAME:-localhost}"
      PHAIDRA_HOSTPORT: "${PHAIDRA_HOSTPORT:-8899}"
      ADMIN_IP_LIST: "${ADMIN_IP_LIST:-10.0.2.2}"
    entrypoint:
      - bash
      - /mnt/startup/httpd-demo-startup.bash

  imageserver:
    image: testuser34/imageserver-base:979c59b3
    pull_policy: always
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    volumes:
      - s3_cache:/s3_cache:ro
    networks:
      - phaidra-network

  solr:
    image: solr:9.6.1
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    volumes:
      - solr:/var/solr
      - ../container_init/solr:/mnt/solr:ro
    entrypoint:
      - bash
      - /mnt/solr/solr_entrypoint.bash
    environment:
      SOLR_USER: "${SOLR_USER:-phaidra}"
      SOLR_PASS: "${SOLR_PASS:-phaidra}"
    networks:
      - phaidra-network

  ui:
    depends_on:
      - api
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    # reference your custom image here, if you've created one from compose_dev and pushed to a registry.
    image: testuser34/ui-dist:latest
    pull_policy: always
    networks:
      - phaidra-network
    environment:
      PHAIDRA_HOSTNAME: "${PHAIDRA_HOSTNAME:-localhost}"
      PHAIDRA_PORTSTUB: "${PHAIDRA_PORTSTUB:-:}"
      PHAIDRA_HOSTPORT: "${PHAIDRA_HOSTPORT:-8899}"
      OUTSIDE_HTTP_SCHEME: "${OUTSIDE_HTTP_SCHEME:-http}"
      PHAIDRA_PRIMARY_COLOR: "${PHAIDRA_PRIMARY_COLOR:-#008080}"
      PHAIDRA_DEFAULT_LANGUAGE: "${PHAIDRA_DEFAULT_LANGUAGE:-eng}"
      PHAIDRA_API_HOST_INTERNAL: "${PHAIDRA_API_HOST_INTERNAL:-api}"

  api:
    depends_on:
      - mariadb-phaidra
      - mongodb-phaidra
      - fedora
    image: testuser34/api-base-s3:20240703-init-v1
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    pull_policy: always
    volumes:
      - s3_cache:/s3_cache
      - ../src/phaidra-api:/usr/local/phaidra/phaidra-api:ro
      - ../container_init/api/api-entrypoint.bash:/mnt/api-entrypoint.bash:ro
    networks:
      - phaidra-network
    environment:
      PHAIDRA_HOSTNAME: "${PHAIDRA_HOSTNAME:-localhost}"
      PHAIDRA_PORTSTUB: "${PHAIDRA_PORTSTUB:-:}"
      PHAIDRA_HOSTPORT: "${PHAIDRA_HOSTPORT:-8899}"
      OUTSIDE_HTTP_SCHEME: "${OUTSIDE_HTTP_SCHEME:-http}"
      PHAIDRA_SECRET: "${PHAIDRA_SECRET:-changeme}"
      PHAIDRA_ENCRYPTION_KEY: "${PHAIDRA_ENCRYPTION_KEY:-changeme}"
      IMAGESERVER_HASH_SECRET: "${IMAGESERVER_HASH_SECRET:-changeme}"
      PHAIDRA_ADMIN_USER: "${PHAIDRA_ADMIN_USER:-phaidraAdmin}"
      PHAIDRA_ADMIN_PASSWORD: "${PHAIDRA_ADMIN_PASSWORD:-12345}"
      FEDORA_ADMIN_USER: "${FEDORA_ADMIN_USER:-fedoraAdmin}"
      FEDORA_ADMIN_PASS: "${FEDORA_ADMIN_PASS:-1234}"
      SOLR_USER: "${SOLR_USER:-phaidra}"
      SOLR_PASS: "${SOLR_PASS:-phaidra}"
      LDAP_ADMIN_USERNAME: "${LDAP_ADMIN_USERNAME:-admin}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD:-adminpassword}"
      LDAP_ROOT: "dc=${LDAP_SLD:-example},dc=${LDAP_TLD:-org}"
      OC_EXTERNAL: "${OC_EXTERNAL:-false}"
      FEDORA_OCFL_ROOT: "${FEDORA_OCFL_ROOT:-/mnt/fedora/data/ocfl-root}"
      SOLR_HOST: "${SOLR_HOST:-solr}"
      FEDORA_HOST: "${FEDORA_HOST:-fedora}"
      IMAGESERVER_HOST: "${IMAGESERVER_HOST:-imageserver}"
      OPENLDAP_HOST: "${OPENLDAP_HOST:-openldap}"
      MONGODB_PHAIDRA_HOST: "${MONGODB_PHAIDRA_HOST:-mongodb-phaidra}"
      MONGODB_PHAIDRA_USER: "${MONGODB_PHAIDRA_USER:-phaidra}"
      MONGODB_PHAIDRA_PASSWORD: "${MONGODB_PHAIDRA_PASSWORD:-phaidra}"
      MARIADB_PHAIDRA_HOST: "${MONGODB_PHAIDRA_HOST:-mariadb-phaidra}"
      MARIADB_PHAIDRA_USER: "${MARIADB_PHAIDRA_USER:-phaidra}"
      MARIADB_PHAIDRA_PASSWORD: "${MARIADB_PHAIDRA_PASSWORD:-phaidra}"
      S3_ENABLED: "${S3_ENABLED:-false}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY:-}"
      S3_SECRET_KEY: "${S3_SECRET_KEY:-}"
      S3_BUCKETNAME: "${S3_BUCKETNAME:-}"
      S3_CACHE_TOPDIR: "${S3_CACHE_TOPDIR:-}"
      S3_CACHESIZE: "${S3_CACHESIZE:-1000000}"
      SHIB_USERNAME: "${SHIB_USERNAME:-}"
      SHIB_SURNAME: "${SHIB_SURNAME:-}"
      SHIB_GIVEN_NAME: "${SHIB_GIVEN_NAME:-}"
      SHIB_AFFILIATION: "${SHIB_AFFILIATION:-}"
      SHIB_MAIL: "${SHIB_MAIL:-}"
      SHIB_REQUIRED_AFFILIATIONS: "${SHIB_REQUIRED_AFFILIATIONS:-}"
    entrypoint:
      - bash
      - /mnt/api-entrypoint.bash

  pixelgecko:
    depends_on:
      - mongodb-phaidra
      - api
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart:
      always
    image: testuser34/pixelgecko-base-s3:20240702-init-v1
    pull_policy: always
    volumes:
      - ./../src/pixelgecko:/opt/pixelgecko:ro
    networks:
      - phaidra-network
    environment:
      IMAGE_CONVERSION_INTERVAL: "${IMAGE_CONVERSION_INTERVAL:-5}"
      FEDORA_ADMIN_USER: "${FEDORA_ADMIN_USER:-fedoraAdmin}"
      FEDORA_ADMIN_PASS: "${FEDORA_ADMIN_PASS:-1234}"
      S3_ENABLED: "${S3_ENABLED:-false}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY:-}"
      S3_SECRET_KEY: "${S3_SECRET_KEY:-}"
      S3_BUCKETNAME: "${S3_BUCKETNAME:-}"

  mariadb-phaidra:
    image: mariadb:11.0.2-jammy
    restart: always
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_PHAIDRA_ROOT_PASSWORD:-example}"
      MARIADB_DATABASE: "${PHAIDRADB:-phaidradb}"
      MARIADB_USER: "${MARIADB_PHAIDRA_USER:-phaidra}"
      MARIADB_PASSWORD: "${MARIADB_PHAIDRA_PASSWORD:-phaidra}"
    volumes:
      - .././container_init/mariadb/phaidradb:/docker-entrypoint-initdb.d:ro
      - mariadb_phaidra:/var/lib/mysql
    networks:
      - phaidra-network

  mariadb-fedora:
    image: mariadb:10.5
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_FEDORA_ROOT_PASSWORD:-example}"
      MARIADB_DATABASE: "${FEDORADB:-fedoradb}"
      MARIADB_USER: "${MARIADB_FEDORA_USER:-phaidra}"
      MARIADB_PASSWORD: "${MARIADB_FEDORA_PASSWORD:-phaidra}"
    volumes:
      - .././container_init/mariadb/fedoradb:/docker-entrypoint-initdb.d:ro
      - mariadb_fedora:/var/lib/mysql
    networks:
      - phaidra-network

  mongodb-phaidra:
    image: mongo:5
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_PHAIDRA_USER:-phaidra}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PHAIDRA_PASSWORD:-phaidra}"
    volumes:
      - mongodb_phaidra:/data/db
      - .././container_init/mongodb/init_oai_sets.json:/mnt/init_oai_sets.json:ro
      - .././container_init/mongodb/mongodb-after-entry.sh:/docker-entrypoint-initdb.d/mongodb-after-entry.sh:ro
    networks:
      - phaidra-network

  dbgate:
    image: dbgate/dbgate:5.2.7
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: always
    environment:
      CONNECTIONS: con1,con2,con3
      LABEL_con1: MariaDB-Phaidra
      SERVER_con1: "${MARIADB_PHAIDRA_HOST:-mariadb-phaidra}"
      USER_con1: "${MARIADB_PHAIDRA_USER:-phaidra}"
      PASSWORD_con1: "${MARIADB_PHAIDRA_PASSWORD:-phaidra}"
      PORT_con1: 3306
      ENGINE_con1: mariadb@dbgate-plugin-mysql
      LABEL_con2: MariaDB-Fedora
      SERVER_con2: "${MARIADB_FEDORA_HOST:-mariadb-fedora}"
      USER_con2: "${MARIADB_FEDORA_USER:-phaidra}"
      PASSWORD_con2: "${MARIADB_FEDORA_PASSWORD:-phaidra}"
      PORT_con2: 3306
      ENGINE_con2: mariadb@dbgate-plugin-mysql
      LABEL_con3: MongoDB-Phaidra
      URL_con3: "mongodb://${MONGODB_PHAIDRA_USER:-phaidra}:${MONGODB_PHAIDRA_PASSWORD:-phaidra}@${MONGODB_PHAIDRA_HOST:-mongodb-phaidra}:27017"
      ENGINE_con3: mongo@dbgate-plugin-mongo
      WEB_ROOT: /dbgate
      LOGINS: phaidra
      LOGIN_PASSWORD_phaidra: "${DBGATE_PASS:-phaidra}"
    volumes:
      - dbgate:/root/.dbgate
    depends_on:
      - mariadb-phaidra
      - mariadb-fedora
      - mongodb-phaidra
    networks:
      - phaidra-network

  fedora:
    image: fcrepo/fcrepo:6.4.1
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: always
    environment:
      CATALINA_OPTS: "-Dfcrepo.db.url=jdbc:mariadb://mariadb-fedora:3306/fedoradb -Dfcrepo.db.user=phaidra -Dfcrepo.db.password=phaidra -Dfcrepo.storage=ocfl-s3 -Dfcrepo.aws.region=${S3_REGION} -Dfcrepo.ocfl.s3.bucket=${S3_BUCKETNAME} -Dfcrepo.aws.access-key=${S3_ACCESS_KEY} -Dfcrepo.aws.secret-key=${S3_SECRET_KEY} -Dfcrepo.ocfl.s3.prefix=fedora"
      FEDORA_ADMIN_USERNAME: "${FEDORA_ADMIN_USER:-fedoraAdmin}"
      FEDORA_ADMIN_PASSWORD: "${FEDORA_ADMIN_PASS:-1234}"
    depends_on:
      - mariadb-fedora
    networks:
      - phaidra-network

  lam:
    image: ghcr.io/ldapaccountmanager/lam:8.5
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: always
    environment:
      LDAP_DOMAIN: "${LDAP_SLD:-example}.${LDAP_TLD:-org}"
      LDAP_SERVER: "${LDAP_PROTOCOL:-ldap}://${LDAP_HOSTNAME:-openldap}:${LDAP_PORT_NUMBER:-1389}"
      LDAP_USER: "cn=${LDAP_ADMIN_USERNAME:-admin},dc=${LDAP_SLD:-example},dc=${LDAP_TLD:-org}"
      LDAP_USERS_DN: "ou=${LDAP_USERS_OU:-people},dc=${LDAP_SLD:-example},dc=${LDAP_TLD:-org}"
      LDAP_GROUPS_DN: "ou=${LDAP_GROUPS_OU:-groups},dc=${LDAP_SLD:-example},dc=${LDAP_TLD:-org}"
    depends_on:
      - openldap
    networks:
      - phaidra-network

  openldap:
    image: bitnami/openldap:2.6.6-debian-11-r59
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    environment:
      LDAP_ADMIN_USERNAME: "${LDAP_ADMIN_USERNAME:-admin}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD:-adminpassword}"
      LDAP_PORT_NUMBER: "${LDAP_PORT_NUMBER:-1389}"
      LDAP_ROOT: "dc=${LDAP_SLD:-example},dc=${LDAP_TLD:-org}"
      LDAP_CUSTOM_LDIF_DIR: "/ldifs"
    volumes:
      - openldap:/bitnami/openldap
      - .././container_init/openldap:/ldifs:ro
    networks:
      - phaidra-network

  chronos:
    image: testuser34/chronos-base:73e15d1c
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    pull_policy: always
    volumes:
      - chronos-database-dumps:/mnt/database-dumps
      - chronos-sitemaps:/mnt/sitemaps
      - chronos-oai-logs:/mnt/oai-logs
      - .././container_init/chronos:/mnt/chronos:ro
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD:-example}"
      PHAIDRADB: "${PHAIDRADB:-phaidradb}"
      FEDORADB: "${FEDORADB:-fedoradb}"
      MONGODB_PHAIDRA_USER: "${MONGODB_PHAIDRA_USER:-phaidra}"
      MONGODB_PHAIDRA_PASSWORD: "${MONGODB_PHAIDRA_PASSWORD:-phaidra}"
      PHAIDRA_HOSTNAME: "${PHAIDRA_HOSTNAME:-localhost}"
      PHAIDRA_PORTSTUB: "${PHAIDRA_PORTSTUB:-:}"
      PHAIDRA_HOSTPORT: "${PHAIDRA_HOSTPORT:-8899}"
      OUTSIDE_HTTP_SCHEME: "${OUTSIDE_HTTP_SCHEME:-http}"
      PHAIDRA_ADMIN_USER: "${PHAIDRA_ADMIN_USER:-phaidraAdmin}"
      PHAIDRA_ADMIN_PASSWORD: "${PHAIDRA_ADMIN_PASSWORD:-12345}"
      FEDORA_ADMIN_USER: "${FEDORA_ADMIN_USER:-fedoraAdmin}"
      FEDORA_ADMIN_PASS: "${FEDORA_ADMIN_PASS:-1234}"
      SOLR_HOST: "${SOLR_HOST:-solr}"
      MARIADB_FEDORA_HOST: "${MARIADB_FEDORA_HOST:-mariadb-fedora}"
      MARIADB_PHAIDRA_HOST: "${MARIADB_PHAIDRA_HOST:-mariadb-phaidra}"
      MONGODB_PHAIDRA_HOST: "${MONGODB_PHAIDRA_HOST:-mongodb-phaidra}"
      FEDORA_HOST: "${FEDORA_HOST:-fedora}"
    depends_on:
      - mariadb-fedora
      - mariadb-phaidra
      - mongodb-phaidra
    entrypoint:
      - bash
      - /mnt/chronos/chronos-entrypoint.bash
    networks:
      - phaidra-network

  promtail-local:
    image: grafana/promtail:3.0.0
    volumes:
      - .././container_init/promtail/promtail-local-config.yaml:/etc/promtail/config.yaml:ro
      - ${HOST_DOCKER_SOCKET}:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yaml -config.expand-env=true
    networks:
      - phaidra-network
    depends_on:
      - grafana

  loki:
    image: grafana/loki:3.0.0
    volumes:
      - .././container_init/loki/loki-docker-config.yaml:/etc/loki/local-config.yaml:ro
      - loki:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - phaidra-network

  grafana:
    image: grafana/grafana:11.0.0
    volumes:
      - .././container_init/grafana/ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml:ro
      - .././container_init/grafana/dd.yaml:/etc/grafana/provisioning/dashboards/dd.yaml:ro
      - ../container_init/grafana/dashboards:/mnt/grafana/dashboards:ro
      - grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER:-phaidra}"
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD:-phaidra}"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/mnt/grafana/dashboards/phaidra_default.json"
    depends_on:
      - loki
    networks:
      - phaidra-network

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ../container_init/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - phaidra-network

  node-exporter:
    image: prom/node-exporter:v1.8.1
    networks:
      - phaidra-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    networks:
      - phaidra-network
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ${HOST_DOCKER_SOCKET}:/var/run/docker.sock:ro

  # UNCOMMENT and fill .env values if you have access to an opencast instance
  # vige:
  #   image: testuser34/vige-base:f10c5205
  #   labels:
  #     logging: "promtail"
  #     logging_jobname: "containerlogs"
  #   pull_policy: always
  #   volumes:
  #     - .././src/vige:/mnt/vige:ro
  #     - vige:/opt/vige
  #     - fedora:/mnt/fedora:ro
  #     - vige-mongosh:/root/.mongodb
  #   networks:
  #     - phaidra-network
  #   depends_on:
  #     - mongodb-phaidra
  #   environment:
  #     OC_EVENTS_URL: ${OC_EVENTS_URL}
  #     OC_INGEST_URL: ${OC_INGEST_URL}
  #     OC_USER: ${OC_USER}
  #     OC_PASS: ${OC_PASS}
  #     OC_WORKFLOW: ${OC_WORKFLOW}
  #     M_USER: ${MONGODB_PHAIDRA_USER}
  #     M_PASS: ${MONGODB_PHAIDRA_PASSWORD}
  #     M_AGENT_DB: ${MONGO_AGENT_DB}
  #   command:
  #     - bash
  #     - /mnt/vige/vige_controller.bash

  # UNCOMMENT and fill .env values, if you have a remote Grafana instance with loki.
  # promtail-push:
  #   image: grafana/promtail:3.0.0
  #   volumes:
  #     - .././container_init/promtail/promtail-push-config.yaml:/etc/promtail/config.yaml:ro
  #     - ${HOST_DOCKER_SOCKET}:/var/run/docker.sock:ro
  #   command: -config.file=/etc/promtail/config.yaml -config.expand-env=true
  #   networks:
  #     - phaidra-network
  #   environment:
  #     - LOKI_PUSH_URL=${LOKI_PUSH_URL}
  #     - PROMTAIL_HOST_LABEL=${PROMTAIL_HOST_LABEL}

volumes:
  openldap:
  dbgate:
  mongodb_phaidra:
  mariadb_fedora:
  mariadb_phaidra:
  pixelgecko:
  solr:
  chronos-database-dumps:
  chronos-sitemaps:
  chronos-oai-logs:
  vige:
  vige-mongosh:
  loki:
  grafana:
  prometheus:
  s3_cache:
