version: '3'

name: phaidra

services:

  imageserver:
    build:
      context: .
      dockerfile: dockerfiles/imageserver.dockerfile
    ports:
      - "8081:80"
    volumes:
      - pixelgecko:/mnt/converted_images:ro

  solr:
    build:
      context: .
      dockerfile: dockerfiles/solr.dockerfile
    volumes:
      - solr:/var/solr
    command:
      - solr-precreate
      - phaidra
      - /tmp/phaidra
    ports:
      - "8983:8983"

  ui:
    depends_on:
      - api
    build:
      context: .
      dockerfile: dockerfiles/ui.dockerfile
    ports:
      - "3001:3001"

  api:
    depends_on:
      - mariadb-phaidra
      - mongodb-phaidra
      - fedora
    build:
      context: .
      dockerfile: dockerfiles/api.dockerfile
    volumes:
      - api_logs:/var/log/phaidra
      - fedora:/mnt/fedora:ro
    ports:
      - "3000:3000"

  pixelgecko:
    depends_on:
      - mongodb-phaidra
      - api
    restart:
      always
    build:
      context: .
      dockerfile: dockerfiles/pixelgecko.dockerfile
    volumes:
      - fedora:/mnt/fedora:ro
      - pixelgecko:/mnt/converted_images

  mariadb-phaidra:
    image: mariadb:11.0.2-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${PHAIDRADB}
      MARIADB_USER: ${MARIADB_PHAIDRA_USER}
      MARIADB_PASSWORD: ${MARIADB_PHAIDRA_PASSWORD}
    volumes:
      - ./container_configs/mariadb/phaidradb.sql.gz:/docker-entrypoint-initdb.d/phaidradb.sql.gz:ro
      - mariadb_phaidra:/var/lib/mysql

  mariadb-fedora:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${FEDORADB}
      MARIADB_USER: ${MARIADB_PHAIDRA_USER}
      MARIADB_PASSWORD: ${MARIADB_PHAIDRA_PASSWORD}
    volumes:
      - mariadb_fedora:/var/lib/mysql

  mongodb-phaidra:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_PHAIDRA_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PHAIDRA_PASSWORD}
    volumes:
      - mongodb_phaidra:/data/db

  dbgate:
    image: dbgate/dbgate:5.2.5
    restart: always
    environment:
      CONNECTIONS: con1,con2,con3

      LABEL_con1: MariaDB-Phaidra
      SERVER_con1: mariadb-phaidra
      USER_con1: ${MARIADB_PHAIDRA_USER}
      PASSWORD_con1: ${MARIADB_PHAIDRA_PASSWORD}
      PORT_con1: 3306
      ENGINE_con1: mariadb@dbgate-plugin-mysql

      LABEL_con2: MariaDB-Fedora
      SERVER_con2: mariadb-fedora
      USER_con2: ${MARIADB_PHAIDRA_USER}
      PASSWORD_con2: ${MARIADB_PHAIDRA_PASSWORD}
      PORT_con2: 3306
      ENGINE_con2: mariadb@dbgate-plugin-mysql

      LABEL_con3: MongoDB-Phaidra
      URL_con3: mongodb://${MONGODB_PHAIDRA_USER}:${MONGODB_PHAIDRA_PASSWORD}@mongodb-phaidra:27017
      ENGINE_con3: mongo@dbgate-plugin-mongo

      WEB_ROOT: /dbgate

    volumes:
      - dbgate:/root/.dbgate
    depends_on:
      - mariadb-phaidra
      - mariadb-fedora
      - mongodb-phaidra
    ports:
      - "7777:3000"

  fedora:
    image: fcrepo/fcrepo:6.4.0
    restart: always
    environment:
      - CATALINA_OPTS=${CATALINA_OPTS}
    volumes:
      - fedora:/usr/local/tomcat/fcrepo-home
    depends_on:
      - mariadb-fedora
    ports:
      - "9999:8080"

  lam:
    image: ghcr.io/ldapaccountmanager/lam:8.4
    restart: always
    environment:
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_SERVER=ldap://openldap:${LDAP_PORT_NUMBER}
      - LDAP_USER=cn=${LDAP_ADMIN_USERNAME},${LDAP_ROOT}
      - LDAP_USER_DN=ou=people,${LDAP_ROOT}
      - LDAP_GROUPS_DN=ou=groups,${LDAP_ROOT}
    ports:
      - "8888:80"

  openldap:
    image: bitnami/openldap:2.6.4-debian-11-r44
    environment:
      - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_PORT_NUMBER=${LDAP_PORT_NUMBER}
      - LDAP_ROOT=${LDAP_ROOT}
      - LDAP_CUSTOM_LDIF_DIR=/ldifs
    volumes:
      - openldap:/bitnami/openldap
      - ./container_configs/openldap:/ldifs:ro

volumes:
  api_logs:
  openldap:
  fedora:
  dbgate:
  mongodb_phaidra:
  mariadb_fedora:
  mariadb_phaidra:
  pixelgecko:
  solr:
