site_name: PHAIDRA
site_url: https://phaidra.org
repo_url: https://github.com/phaidra/phaidra
repo_name: phaidra/phaidra
docs_dir: website
theme:
  name: material
  palette:
    primary: white
  logo: assets/media/PHAIDRA/logo/icon-only/PHAIDRA-icon-black.svg
  logo_text: assets/media/PHAIDRA/logo/text-only/PHAIDRA-logo-text-black.svg
  favicon: assets/media/PHAIDRA/logo/icon-only/PHAIDRA-icon-black.svg
  icon:
    repo: fontawesome/brands/github
  custom_dir: website/overrides
  features:
    # - navigation.instant # this messed up the live verion for David with Brave, remove to quickfix, maybe reconsider in the future
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.path

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/phaidraorg/
      name: Follow on Instagram

extra_css:
  - assets/css/reset.css
  - assets/external/css/tailwind.min.css
  - assets/css/landing-page.css
  - assets/css/tooltips.css
  - assets/css/media.css
  - assets/css/tweaks.css

nav:
  - Home: index.md
  - About: about/index.md # talks more to the data steward or high level data manager
  - FAIR Data: fair-data/index.md
  - Documentation: # talks more to the technical people, developers, etc.
    - docs/overview.md
    - Setup:
      - docs/get-started.md
      - docs/features.md
      - docs/customization.md
    - Technical Docs:
      - docs/architecture.md
      - docs/digital-object.md
      - docs/metadata.md
      - docs/vocabularies.md
      - docs/index.md
      - Docked Applications: docs/docked.md
    - API:
      - docs/api.md
      - docs/authorization.md
      - docs/authentication.md
    - User Interface:
      - User Interface: docs/ui.md
  - Media: media/index.md
  - Community: 
    - Overview: community/overview.md
    - List of Partner Institutions: community/list-of-partners.md
    - All Partners:
      - Austria:
        - Academy of Fine Arts Vienna: community/academy-of-fine-arts-vienna.md
        - Anton Bruckner Private University: community/anton-bruckner-private-university.md
        - Carinthia University of Applied Sciences: https://www.fh-kaernten.at/en/
        - Gustav Mahler Private University for Music: community/gustav-mahler-private-university-for-music.md
        - University College of Christian Churches of Teacher Education Vienna/Krems: community/kph-vienna-krems.md
        - St. Pölten University of Applied Sciences: community/st-poelten-university-of-applied-sciences.md
        - Austrian Science Fund - FWF: community/austrian-science-fund-fwf.md
        - Council of Austrian University Libraries (ubifo): community/council-of-austrian-university-libraries-ubifo.md
        - University of Arts Linz: community/university-of-arts-linz.md
        - University of Applied Arts Vienna: community/university-of-applied-arts-vienna.md
        - University of Music and Performing Arts Graz: community/university-of-music-and-performing-arts-graz.md
        - University of Vienna: community/university-of-vienna.md
        - Danube University Krems - University for Continuing Education: community/university-for-continuing-education-krems.md
        - University of Veterinary Medicine Vienna: community/university-of-veterinary-medicine-vienna.md
        - Vorarlberger Landesbibliothek: community/vorarlberger-landesbibliothek.md
      - Bosnia and Herzegovina:
        - Univerzitet u Banjoj Luci: community/univerzitet-u-banjoj-luci.md
        - Univerzitet u Sarajevu: https://www.unsa.ba/
        - Univerzitet u Tuzli: https://www.untz.ba/
      - Italy:
        - Università Ca Foscari: community/universita-ca-foscari-venezia.md
        - Università Iuav di Venezia: https://www.iuav.it/homepage/index.htm
        - Università di Padova: community/universita-di-padova.md
      - Montenegro:
        - Univerzitet Crne Gore: community/univerzitet-crne-gore.md
      - Serbia:
        - Univerzitet u Beogradu: community/univerzitet-u-beogradu.md
        - Univerzitet u Kragujevcu: community/univerzitet-u-kragujevcu.md
        - Univerzitet u Nišu: community/univerzitet-u-nisu.md

plugins:
  - search
  - privacy
  - redirects:
      redirect_maps:
        # https://github.com/mkdocs/mkdocs-redirects
        'resources.md': 'index.md'
        'community/phaidra-partners.md': 'community/list-of-partners.md'

# plugins:
#   - redirects:
#       redirect_maps:
#         # redirects urls from old phaidra.org website to new pages
#         # old: community/university-x
#         # new: community/partners/university-x
#         # the reasoning behind this is to enable folder structure for all the external pages within /partners
#         # having folder structure with custom urls is not possible
#         'community/anton-bruckner-private-university.md': 'community/partners/anton-bruckner-private-university.md'
#         'community/st-poelten-university-of-applied-sciences.md': 'community/partners/st-poelten-university-of-applied-sciences.md'
#         'community/austrian-science-fund-fwf.md': 'community/partners/austrian-science-fund-fwf.md'
#         'community/council-of-austrian-university-libraries-ubifo.md': 'community/partners/council-of-austrian-university-libraries-ubifo.md'
#         'community/university-of-arts-linz.md': 'community/partners/university-of-arts-linz.md'
#         'community/university-of-applied-arts-vienna.md': 'community/partners/university-of-applied-arts-vienna.md'
#         'community/university-of-music-and-performing-arts-graz.md': 'community/partners/university-of-music-and-performing-arts-graz.md'
#         'community/university-of-vienna.md': 'community/partners/university-of-vienna.md'
#         'community/university-for-continuing-education-krems.md': 'community/partners/university-for-continuing-education-krems.md'
#         'community/university-of-veterinary-medicine-vienna.md': 'community/partners/university-of-veterinary-medicine-vienna.md'
#         'community/vorarlberger-landesbibliothek.md': 'community/partners/vorarlberger-landesbibliothek.md'
#         'community/univerzitet-u-banjoj-luci.md': 'community/partners/univerzitet-u-banjoj-luci.md'
#         'community/universita-ca-foscari-venezia.md': 'community/partners/universita-ca-foscari-venezia.md'
#         'community/universita-di-padova.md': 'community/partners/universita-di-padova.md'
#         'community/univerzitet-crne-gore.md': 'community/partners/univerzitet-crne-gore.md'
#         'community/univerzitet-u-beogradu.md': 'community/partners/univerzitet-u-beogradu.md'
#         'community/univerzitet-u-kragujevcu.md': 'community/partners/univerzitet-u-kragujevcu.md'
#         'community/univerzitet-u-nisu.md': 'community/partners/univerzitet-u-nisu.md'
