version: '3'

name: phaidra-ssl

networks:
  phaidra-network:
    ipam:
      config:
        - subnet: 172.29.0.0/16
          ip_range: 172.29.7.0/24
          gateway: 172.29.5.1

services:

  httpd:
    image: testuser34/httpd-base:latest
    pull_policy: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .././container_init/httpd/phaidra-ssl:/mnt/startup:ro
      - .././docs:/mnt/docs:ro
      - chronos-sitemaps:/mnt/sitemaps:ro
    depends_on:
      - api
      - ui
    networks:
      - phaidra-network
    environment:
      - PHAIDRA_HOSTNAME=${PHAIDRA_HOSTNAME}
      - PRIVILEGED_IP=${ALLOWED_HOST}
    entrypoint:
      - bash
      - /mnt/startup/httpd-ssl-startup.bash

  imageserver:
    image: testuser34/imageserver-base:latest
    pull_policy: always
    volumes:
      - pixelgecko:/mnt/converted_images:ro
    networks:
      - phaidra-network

  solr:
    image: solr:9.2.1    
    volumes:
      - solr:/var/solr
      - ./../container_init/solr/phaidra_core:/tmp/phaidra:ro      
    command:
      - solr-precreate
      - phaidra
      - /tmp/phaidra
    networks:
      - phaidra-network

  ui:
    depends_on:
      - api
    build:
      context: ../.
      dockerfile: dockerfiles/ui.dockerfile
      args:
        PHAIDRA_HOSTNAME: ${PHAIDRA_HOSTNAME}
        PHAIDRA_PORTSTUB: ${PHAIDRA_PORTSTUB}
        PHAIDRA_HOSTPORT: ${PHAIDRA_HOSTPORT}
        OUTSIDE_HTTP_SCHEME: ${OUTSIDE_HTTP_SCHEME}
    networks:
      - phaidra-network

  api:
    depends_on:
      - mariadb-phaidra
      - mongodb-phaidra
      - fedora
    image: testuser34/api-base:latest
    pull_policy: always
    volumes:
      - api_logs:/var/log/phaidra
      - fedora:/mnt/fedora:ro
      - ../src/phaidra-api:/usr/local/phaidra/phaidra-api:ro
    networks:
      - phaidra-network
    environment:
      - PHAIDRA_HOSTNAME=${PHAIDRA_HOSTNAME}
      - PHAIDRA_PORTSTUB=${PHAIDRA_PORTSTUB}
      - PHAIDRA_HOSTPORT=${PHAIDRA_HOSTPORT}
      - OUTSIDE_HTTP_SCHEME=${OUTSIDE_HTTP_SCHEME}
      - PHAIDRA_SECRET=${PHAIDRA_SECRET}
      - PHAIDRA_ENCRYPTION_KEY=${PHAIDRA_ENCRYPTION_KEY}
      - IMAGESERVER_HASH_SECRET=${IMAGESERVER_HASH_SECRET}
      - PHAIDRA_ADMIN_USER=${PHAIDRA_ADMIN_USER}
      - PHAIDRA_ADMIN_PASSWORD=${PHAIDRA_ADMIN_PASSWORD}
      - FEDORA_ADMIN_USER=${FEDORA_ADMIN_USER}
      - FEDORA_ADMIN_PASS=${FEDORA_ADMIN_PASS}

  pixelgecko:
    depends_on:
      - mongodb-phaidra
      - api
    restart:
      always
    image: testuser34/pixelgecko-base:latest
    pull_policy: always
    volumes:
      - fedora:/mnt/fedora:ro
      - pixelgecko:/mnt/converted_images
      - ./../src/pixelgecko:/opt/pixelgecko:ro
    networks:
      - phaidra-network
    environment:
      - IMAGE_CONVERSION_INTERVAL=${IMAGE_CONVERSION_INTERVAL}

  mariadb-phaidra:
    image: mariadb:11.0.2-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${PHAIDRADB}
      MARIADB_USER: ${MARIADB_PHAIDRA_USER}
      MARIADB_PASSWORD: ${MARIADB_PHAIDRA_PASSWORD}
    volumes:
      - .././container_init/mariadb/phaidradb.sql.gz:/docker-entrypoint-initdb.d/phaidradb.sql.gz:ro
      - mariadb_phaidra:/var/lib/mysql
    networks:
      - phaidra-network

  mariadb-fedora:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${FEDORADB}
      MARIADB_USER: ${MARIADB_PHAIDRA_USER}
      MARIADB_PASSWORD: ${MARIADB_PHAIDRA_PASSWORD}
    volumes:
      - mariadb_fedora:/var/lib/mysql
    networks:
      - phaidra-network

  mongodb-phaidra:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_PHAIDRA_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PHAIDRA_PASSWORD}
    volumes:
      - mongodb_phaidra:/data/db
      - .././container_init/mongodb/init_oai_sets.json:/mnt/init_oai_sets.json:ro
      - .././container_init/mongodb/mongodb-after-entry.sh:/docker-entrypoint-initdb.d/mongodb-after-entry.sh:ro
    networks:
      - phaidra-network

  dbgate:
    image: dbgate/dbgate:5.2.6
    restart: always
    environment:
      CONNECTIONS: con1,con2,con3
      LABEL_con1: MariaDB-Phaidra
      SERVER_con1: mariadb-phaidra
      USER_con1: ${MARIADB_PHAIDRA_USER}
      PASSWORD_con1: ${MARIADB_PHAIDRA_PASSWORD}
      PORT_con1: 3306
      ENGINE_con1: mariadb@dbgate-plugin-mysql
      LABEL_con2: MariaDB-Fedora
      SERVER_con2: mariadb-fedora
      USER_con2: ${MARIADB_PHAIDRA_USER}
      PASSWORD_con2: ${MARIADB_PHAIDRA_PASSWORD}
      PORT_con2: 3306
      ENGINE_con2: mariadb@dbgate-plugin-mysql
      LABEL_con3: MongoDB-Phaidra
      URL_con3: mongodb://${MONGODB_PHAIDRA_USER}:${MONGODB_PHAIDRA_PASSWORD}@mongodb-phaidra:27017
      ENGINE_con3: mongo@dbgate-plugin-mongo
      WEB_ROOT: /dbgate
    volumes:
      - dbgate:/root/.dbgate
    depends_on:
      - mariadb-phaidra
      - mariadb-fedora
      - mongodb-phaidra
    networks:
      - phaidra-network

  fedora:
    image: fcrepo/fcrepo:6.4.0
    restart: always
    environment:
      - CATALINA_OPTS=${CATALINA_OPTS}
      - FEDORA_ADMIN_USERNAME=${FEDORA_ADMIN_USER}
      - FEDORA_ADMIN_PASSWORD=${FEDORA_ADMIN_PASS}
    volumes:
      - fedora:/usr/local/tomcat/fcrepo-home
    depends_on:
      - mariadb-fedora
    networks:
      - phaidra-network

  lam:
    image: ghcr.io/ldapaccountmanager/lam:8.5
    restart: always
    environment:
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_SERVER=ldap://openldap:${LDAP_PORT_NUMBER}
      - LDAP_USER=cn=${LDAP_ADMIN_USERNAME},${LDAP_ROOT}
      - LDAP_USERS_DN=ou=people,${LDAP_ROOT}
      - LDAP_GROUPS_DN=ou=groups,${LDAP_ROOT}
    networks:
      - phaidra-network

  openldap:
    image: bitnami/openldap:2.6.6-debian-11-r59
    environment:
      - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_PORT_NUMBER=${LDAP_PORT_NUMBER}
      - LDAP_ROOT=${LDAP_ROOT}
      - LDAP_CUSTOM_LDIF_DIR=/ldifs
    volumes:
      - openldap:/bitnami/openldap
      - .././container_init/openldap:/ldifs:ro
    networks:
      - phaidra-network

  chronos:
    image: testuser34/chronos-base:latest
    pull_policy: always
    volumes:
      - chronos-database-dumps:/mnt/database-dumps
      - chronos-sitemaps:/mnt/sitemaps
      - chronos-oai-logs:/mnt/oai-logs
      - .././container_init/chronos:/mnt/chronos:ro
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - PHAIDRADB=${PHAIDRADB}
      - FEDORADB=${FEDORADB}
      - MONGODB_PHAIDRA_USER=${MONGODB_PHAIDRA_USER}
      - MONGODB_PHAIDRA_PASSWORD=${MONGODB_PHAIDRA_PASSWORD}
      - PHAIDRA_HOSTNAME=${PHAIDRA_HOSTNAME}
      - PHAIDRA_PORTSTUB=${PHAIDRA_PORTSTUB}
      - PHAIDRA_HOSTPORT=${PHAIDRA_HOSTPORT}
      - OUTSIDE_HTTP_SCHEME=${OUTSIDE_HTTP_SCHEME}
    depends_on:
      - mariadb-fedora
      - mariadb-phaidra
      - mongodb-phaidra
    entrypoint:
      - bash
      - /mnt/chronos/chronos-entrypoint.bash
    networks:
      - phaidra-network

volumes:
  api_logs:
  openldap:
  fedora:
  dbgate:
  mongodb_phaidra:
  mariadb_fedora:
  mariadb_phaidra:
  pixelgecko:
  solr:
  chronos-database-dumps:
  chronos-sitemaps:
  chronos-oai-logs:
