apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    phaidra.app: api
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      phaidra.app: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        promtail.io/scrape: 'true'
        checksum/config: {{ include (print $.Template.BasePath "/api-configmap.yaml") . | sha256sum }}
      labels:
        phaidra.app: api
    spec:
      containers:
        - env:
            - name: "FEDORA_ADMIN_PASS"
              value: "{{ .Values.FEDORA_ADMIN_PASS }}"
            - name: "FEDORA_ADMIN_USER"
              value: "{{ .Values.FEDORA_ADMIN_USER }}"
            - name: "FEDORA_OCFL_ROOT"
              value: "{{ .Values.FEDORA_OCFL_ROOT }}"
            - name: "IMAGESERVER_HASH_SECRET"
              value: "{{ .Values.IMAGESERVER_HASH_SECRET }}"
            - name: "LDAP_ADMIN_PASSWORD"
              value: "{{ .Values.LDAP_ADMIN_PASSWORD }}"
            - name: "LDAP_ADMIN_USERNAME"
              value: "{{ .Values.LDAP_ADMIN_USERNAME }}"
            - name: "LDAP_ROOT"
              value: "{{ .Values.LDAP_ROOT }}"
            - name: "OC_EXTERNAL"
              value: "{{ .Values.OC_EXTERNAL }}"
            - name: "OUTSIDE_HTTP_SCHEME"
              value: "{{ .Values.OUTSIDE_HTTP_SCHEME }}"
            - name: "PHAIDRA_ADMIN_PASSWORD"
              value: "{{ .Values.PHAIDRA_ADMIN_PASSWORD }}"
            - name: "PHAIDRA_ADMIN_USER"
              value: "{{ .Values.PHAIDRA_ADMIN_USER }}"
            - name: "PHAIDRA_ENCRYPTION_KEY"
              value: "{{ .Values.PHAIDRA_ENCRYPTION_KEY }}"
            - name: "PHAIDRA_HOSTNAME"
              value: "{{ .Values.PHAIDRA_HOSTNAME }}"
            - name: "PHAIDRA_HOSTPORT"
              value: "{{ .Values.PHAIDRA_HOSTPORT }}"
            - name: "PHAIDRA_PORTSTUB"
              value: "{{ .Values.PHAIDRA_PORTSTUB }}"
            - name: "PHAIDRA_SECRET"
              value: "{{ .Values.PHAIDRA_SECRET }}"
            - name: "SOLR_PASS"
              value: "{{ .Values.SOLR_PASS }}"
            - name: "SOLR_USER"
              value: "{{ .Values.SOLR_USER }}"
            - name: "SOLR_HOST"
              value: "{{ .Values.SOLR_HOST }}"
          image: testuser34/api-dist:latest
          name: api
          resources: {}
          volumeMounts:
            - mountPath: /mnt/fedora
              name: fedora
              readOnly: true
            - mountPath: /config
              name: api-config
              readOnly: true
          command: ["/bin/sh"]
          args: ["-c", "cp /config/PhaidraAPI.json /usr/local/phaidra/phaidra-api/PhaidraAPI.json && hypnotoad -f phaidra-api.cgi" ]
      restartPolicy: Always
      volumes:
        - name: fedora
          persistentVolumeClaim:
            claimName: fedora-pvc
            readOnly: true
        - name: api-config
          ConfigMap:
            name: api-config
            items:
              - key: "PhaidraAPI.json"
                path: "PhaidraAPI.json"
status: {}
