apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chronos-oai-logs
  name: chronos-oai-logs
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.CHRONOS_OAI_LOGS_PVC_SIZE }}"
status: {}
