apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chronos-sitemaps
  name: chronos-sitemaps
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: "{{ .Values.CHRONOS_SITEMAPS_PVC_TYPE }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.CHRONOS_SITEMAPS_PVC_SIZE }}"
status: {}
