apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    phaidra.app: dbgate
  name: dbgate-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: "{{ .Values.DBGATE_PVC_TYPE }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.DBGATE_PVC_SIZE }}"
status: {}
