apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    logging: promtail
    logging_jobname: containerlogs
  creationTimestamp: null
  labels:
    phaidra.app: dbgate
  name: dbgate
spec:
  replicas: 1
  selector:
    matchLabels:
      phaidra.app: dbgate
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        logging: promtail
        logging_jobname: containerlogs
      creationTimestamp: null
      labels:
        phaidra.network/phaidra-network: "backend"
        phaidra.app: dbgate
    spec:
      containers:
        - env:
            - name: CONNECTIONS
              value: con1,con2,con3
            - name: ENGINE_con1
              value: mariadb@dbgate-plugin-mysql
            - name: ENGINE_con2
              value: mariadb@dbgate-plugin-mysql
            - name: ENGINE_con3
              value: mongo@dbgate-plugin-mongo
            - name: LABEL_con1
              value: MariaDB-Phaidra
            - name: LABEL_con2
              value: MariaDB-Fedora
            - name: LABEL_con3
              value: MongoDB-Phaidra
            - name: LOGINS
              value: phaidra
            - name: LOGIN_PASSWORD_phaidra
              value: "{{ .Values.DBGATE_PASS }}"
            - name: PASSWORD_con1
              value: "{{ .Values.MARIADB_PHAIDRA_PASSWORD }}"
            - name: PASSWORD_con2
              value: "{{ .Values.MARIADB_PHAIDRA_PASSWORD }}"
            - name: PORT_con1
              value: "3306"
            - name: PORT_con2
              value: "3306"
            - name: SERVER_con1
              value: mariadb-phaidra
            - name: SERVER_con2
              value: mariadb-fedora
            - name: URL_con3
            - name: USER_con1
              value: "{{ .Values.MARIADB_PHAIDRA_USER }}"
            - name: USER_con2
              value: "{{ .Values.MARIADB_PHAIDRA_USER }}"
            - name: WEB_ROOT
              value: /dbgate
          image: dbgate/dbgate:5.2.7
          name: dbgate
          resources: {}
          volumeMounts:
            - mountPath: /root/.dbgate
              name: dbgate
      restartPolicy: Always
      volumes:
        - name: dbgate
          persistentVolumeClaim:
            claimName: dbgate
status: {}
