apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    logging: promtail
    logging_jobname: containerlogs
  creationTimestamp: null
  labels:
    phaidra.app: fedora
  name: fedora
spec:
  replicas: 1
  selector:
    matchLabels:
      phaidra.app: fedora
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        logging: promtail
        logging_jobname: containerlogs
      creationTimestamp: null
      labels:
        io.kompose.network/phaidra-network: "true"
        phaidra.app: fedora
    spec:
      containers:
        - env:
            - name: CATALINA_OPTS
              value: "{{ .Values.CATALINA_OPTS }}"
            - name: FEDORA_ADMIN_PASSWORD
              value: "{{ .Values.FEDORA_ADMIN_PASS }}"
            - name: FEDORA_ADMIN_USERNAME
              value: "{{ .Values.FEDORA_ADMIN_USER }}"
          image: fcrepo/fcrepo:6.4.1
          name: fedora
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/tomcat/fcrepo-home
              name: fedora
      restartPolicy: Always
      volumes:
        - name: fedora
          persistentVolumeClaim:
            claimName: fedora
status: {}
