apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: fedora
  name: fedora
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: "{{ .Values.FEDORA_PVC_SIZE }}"
status: {}
