apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    promtail.io/scrape: 'true'
  creationTimestamp: null
  labels:
    phaidra.app: httpd
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      phaidra.app: httpd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        promtail.io/scrape: 'true'
        checksum/config: {{ include (print $.Template.BasePath "/httpd-configmap.yaml") . | sha256sum }}
      creationTimestamp: null
      labels:
        phaidra.network/phaidra-network: "frontend"
        phaidra.app: httpd
    spec:
      containers:
        - env:
            - name: ADMIN_IP_LIST
              value: "{{ .Values.ADMIN_IP_LIST }}"
            - name: PHAIDRA_HOSTNAME
              value: "{{ .Values.PHAIDRA_HOSTNAME }}"
            - name: PHAIDRA_HOSTPORT
              value: "{{ .Values.PHAIDRA_HOSTPORT }}"
            - name: LOAD_BALANCER_IP
              value: "{{ .Values.LOAD_BALANCER_IP }}"
            - name: PHAIDRA_ADMIN_EMAIL
              value: "{{ .Values.PHAIDRA_ADMIN_EMAIL }}"
            - name: SOURCE_CLIENT_IP_HEADER
              value: "{{ .Values.SOURCE_CLIENT_IP_HEADER }}"
          image: httpd:2.4.58-bookworm
          name: httpd
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /mnt/sitemaps
              name: chronos-sitemaps
              readOnly: true
            - mountPath: /config
              name: httpd-config
              readOnly: true
          command: ["/bin/sh"]
          args: [ "-c", "cp /config/httpd.conf /usr/local/apache2/conf/httpd.conf && httpd-foreground"]
      restartPolicy: Always
      volumes:
        - name: chronos-sitemaps
          persistentVolumeClaim:
            claimName: chronos-sitemaps
            readOnly: true
        - name: httpd-config
          configMap:
            name: httpd-config
            items:
              - key: "httpd.conf"
                path: "httpd.conf"
status: {}
