apiVersion: v1
kind: Service
metadata:
  labels:
    phaidra.app: httpd
  name: httpd-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    phaidra.app: httpd
status:
  loadBalancer: {}
