apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-config
data:
  httpd.conf: |
    Listen 0.0.0.0:80
    ServerRoot "/usr/local/apache2"
    ServerAdmin ${PHAIDRA_ADMIN_EMAIL}
    ServerName ${PHAIDRA_HOSTNAME}
    RemoteIPHeader ${SOURCE_CLIENT_IP_HEADER}
    RemoteIPInternalProxy ${LOAD_BALANCER_IP}

    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule authn_file_module modules/mod_authn_file.so
    LoadModule authn_core_module modules/mod_authn_core.so
    LoadModule authz_host_module modules/mod_authz_host.so
    LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
    LoadModule authz_user_module modules/mod_authz_user.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule access_compat_module modules/mod_access_compat.so
    LoadModule auth_basic_module modules/mod_auth_basic.so
    LoadModule reqtimeout_module modules/mod_reqtimeout.so
    LoadModule ext_filter_module modules/mod_ext_filter.so
    LoadModule filter_module modules/mod_filter.so
    LoadModule mime_module modules/mod_mime.so
    LoadModule log_config_module modules/mod_log_config.so
    LoadModule logio_module modules/mod_logio.so
    LoadModule env_module modules/mod_env.so
    LoadModule headers_module modules/mod_headers.so
    LoadModule setenvif_module modules/mod_setenvif.so
    LoadModule version_module modules/mod_version.so
    LoadModule remoteip_module modules/mod_remoteip.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_http_module modules/mod_proxy_http.so
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule status_module modules/mod_status.so
    LoadModule autoindex_module modules/mod_autoindex.so
    LoadModule dir_module modules/mod_dir.so
    LoadModule alias_module modules/mod_alias.so

    <IfModule unixd_module>
        User www-data
        Group www-data
    </IfModule>

    <Directory />
        AllowOverride none
        Require all denied
    </Directory>

    <IfModule dir_module>
        DirectoryIndex index.html
    </IfModule>

    <Files ".ht*">
       Require all denied
    </Files>

    ErrorLog /proc/self/fd/2

    LogLevel warn

    <IfModule log_config_module>
        LogFormat "%h %l %u %t \"%r\" %>s %b" common
        <IfModule logio_module>
            # You need to enable mod_logio.c to use %I and %O
            LogFormat "%a %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
        </IfModule>
        CustomLog /proc/self/fd/1 combined
    </IfModule>

    <IfModule headers_module>
        # Avoid passing HTTP_PROXY environment to CGI's on this or any proxied
        # backend servers which have lingering "httpoxy" defects.
        # 'Proxy' request header is undefined by the IETF, not listed by IANA
        #
        RequestHeader unset Proxy early
    </IfModule>

    <IfModule mime_module>
        TypesConfig conf/mime.types
        AddType application/x-compress .Z
        AddType application/x-gzip .gz .tgz
    </IfModule>

    <VirtualHost 0.0.0.0:80>
        ProxyPreserveHost On
        ProxyRequests off
        DocumentRoot /mnt/sitemaps

        <Location />
            Require all granted
            ProxyPass http://ui:3001/
            ProxyPassReverse http://ui:3001/
        </Location>

        <LocationMatch "^/api/(.*)">
            Require all granted
            ProxyPass http://api-service:3000/$1 timeout=360
            ProxyPassReverse http://api-service:3000/$1
            Proxy100Continue Off
        </LocationMatch>

        <Location /dbgate>
            Require ip ${ADMIN_IP_LIST}
            ProxyPass http://dbgate:3000/dbgate
            ProxyPassReverse http://dbgate:3000/dbgate
        </Location>

        <Location /lam>
            Require ip ${ADMIN_IP_LIST}
            ProxyPass http://lam:80/lam
            ProxyPassReverse http://lam:80/lam
        </Location>

        <Location /fcrepo>
            Require ip ${ADMIN_IP_LIST}
            ProxyPass http://fedora-service:8080/fcrepo
            ProxyPassReverse http://fedora-service:8080/fcrepo
        </Location>

        <Location /solr>
            Require ip ${ADMIN_IP_LIST}
            ProxyPass http://solr-service:8983/solr
            ProxyPassReverse http://solr-service:8983/solr
        </Location>

        <Location /grafana>
            Require ip ${ADMIN_IP_LIST}
            ProxyPass http://grafana:3000/grafana
            ProxyPassReverse http://grafana:3000/grafana
        </Location>

        <LocationMatch "^/sitemap(.*\.xml)$">
            ProxyPass !
        </LocationMatch>

    </VirtualHost>


