apiVersion: v1
kind: Service
metadata:
  annotations:
    logging: promtail
    logging_jobname: containerlogs
  creationTimestamp: null
  labels:
    phaidra.app: httpd
  name: httpd
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    phaidra.app: httpd
status:
  loadBalancer: {}
