apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpd-ingress
  labels:
    phaidra.app: httpd-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  rules:
  - http:
      paths:
      - path: "/(.*)"
        pathType: Prefix
        backend:
          service:
            name: httpd
            port:
              number: 80
