apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../../compose_cloudready/docker-compose.yaml convert
    kompose.version: 1.26.0 (40646f47)
    logging: promtail
    logging_jobname: containerlogs
  creationTimestamp: null
  labels:
    io.kompose.service: httpd
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: httpd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../../compose_cloudready/docker-compose.yaml convert
        kompose.version: 1.26.0 (40646f47)
        logging: promtail
        logging_jobname: containerlogs
      creationTimestamp: null
      labels:
        io.kompose.network/phaidra-network: "true"
        io.kompose.service: httpd
    spec:
      containers:
        - env:
            - name: LOCAL_ADMIN_IP
              value: "{{ .Values.LOCAL_ADMIN_IP }}"
            - name: PHAIDRA_HOSTNAME
              value: "{{ .Values.PHAIDRA_HOSTNAME }}"
            - name: PHAIDRA_HOSTPORT
              value: "{{ .Values.PHAIDRA_HOSTPORT }}"
          image: testuser34/httpd-dist:latest
          name: httpd
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /mnt/sitemaps
              name: chronos-sitemaps
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: chronos-sitemaps
          persistentVolumeClaim:
            claimName: chronos-sitemaps
            readOnly: true
status: {}
