apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../../compose_cloudready/docker-compose.yaml convert
    kompose.version: 1.26.0 (40646f47)
    logging: promtail
    logging_jobname: containerlogs
  creationTimestamp: null
  labels:
    io.kompose.service: httpd
  name: httpd
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: httpd
status:
  loadBalancer: {}
