apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    phaidra.app: loki
  name: loki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      phaidra.app: loki
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        phaidra.app: loki
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/loki-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.8
          resources: {}
          volumeMounts:
            - mountPath: /loki
              name: loki
            - mountPath: /etc/loki
              name: loki-config
              readOnly: true
          args: ["-config.file=/etc/loki/local-config.yaml"]
      restartPolicy: Always
      volumes:
        - name: loki
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: loki-config
          configMap:
            name: loki-config
            items:
              - key: "local-config.yaml"
                path: "local-config.yaml"
status: {}
