apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    phaidra.app: loki
  name: loki
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: "{{ .Values.LOKI_PVC_TYPE }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.LOKI_PVC_SIZE }}"
status: {}
