apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    phaidra.app: loki
  name: loki-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: "{{ .Values.LOKI_PVC_TYPE }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.LOKI_PVC_SIZE }}"
status: {}
