apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    phaidra.app: mariadb-fedora
  name: mariadb-fedora
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: "{{ .Values.MARIADB_FEDORA_PVC_TYPE }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.MARIADB_FEDORA_PVC_SIZE }}"
status: {}
