apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    phaidra.app: mariadb-phaidra
  name: mariadb-phaidra
spec:
  replicas: 1
  selector:
    matchLabels:
      phaidra.app: mariadb-phaidra
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        promtail.io/scrape: 'true'
      creationTimestamp: null
      labels:
        phaidra.network/phaidra-network: "backend"
        phaidra.app: mariadb-phaidra
    spec:
      containers:
        - env:
            - name: MARIADB_DATABASE
              value: "{{ .Values.PHAIDRADB }}"
            - name: MARIADB_PASSWORD
              value: "{{ .Values.MARIADB_PHAIDRA_PASSWORD }}"
            - name: MARIADB_ROOT_PASSWORD
              value: "{{ .Values.MARIADB_ROOT_PASSWORD }}"
            - name: MARIADB_USER
              value: "{{ .Values.MARIADB_PHAIDRA_USER }}"
          image: testuser34/mariadb-phaidra-dist:latest
          name: mariadb-phaidra
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-phaidra
          # run as nobody because of container's chown sequence.
          securityContext:
            runAsUser: 65534
      restartPolicy: Always
      volumes:
        - name: mariadb-phaidra
          persistentVolumeClaim:
            claimName: mariadb-phaidra
status: {}
