apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    phaidra.app: openldap
  name: openldap-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: "{{ .Values.OPENLDAP_PVC_TYPE }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.OPENLDAP_PVC_SIZE }}"
status: {}
