apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pixelgecko
  name: pixelgecko
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: "{{ .Values.PIXELGECKO_PVC_TYPE }}"
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: "{{ .Values.PIXELGECKO_PVC_SIZE }}"
status: {}
