apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    phaidra.app: pixelgecko
  name: pixelgecko-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      phaidra.app: pixelgecko
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        promtail.io/scrape: 'true'
      labels:
        phaidra.app: pixelgecko
    spec:
      containers:
        - env:
            - name: IMAGE_CONVERSION_INTERVAL
              value: "{{ .Values.IMAGE_CONVERSION_INTERVAL }}"
          image: testuser34/pixelgecko-dist:latest
          name: pixelgecko
          resources: {}
          volumeMounts:
            - mountPath: /mnt/fedora
              name: fedora
              readOnly: true
            - mountPath: /mnt/converted_images
              name: pixelgecko
      restartPolicy: Always
      volumes:
        - name: fedora
          persistentVolumeClaim:
            claimName: fedora-pvc
            readOnly: true
        - name: pixelgecko
          persistentVolumeClaim:
            claimName: pixelgecko-pvc
status: {}
