apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: promtail-role
  namespace: phaidra-init
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - services
    - pods
    verbs:
    - get
    - watch
    - list
