apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: promtail-rolebinding
subjects:
    - kind: ServiceAccount
      name: promtail-serviceaccount
      namespace: "{{ .Values.PHAIDRA_K8S_NAMESPACE }}"
roleRef:
    kind: Role
    name: promtail-role
    apiGroup: rbac.authorization.k8s.io
