apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    phaidra.app: solr
  name: solr-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: "{{ .Values.SOLR_PVC_TYPE }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.SOLR_PVC_SIZE }}"
status: {}
