apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    logging: promtail
    logging_jobname: containerlogs
  creationTimestamp: null
  labels:
    phaidra.app: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      phaidra.app: solr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        logging: promtail
        logging_jobname: containerlogs
      creationTimestamp: null
      labels:
        io.kompose.network/phaidra-network: "true"
        phaidra.app: solr
    spec:
      containers:
        - env:
            - name: "SOLR_PASS"
              value: "{{ .Values.SOLR_PASS }}"
            - name: "SOLR_SALT"
              value: "{{ .Values.SOLR_SALT }}"
            - name: "SOLR_USER"
              value: "{{ .Values.SOLR_USER }}"
          image: testuser34/solr-dist:latest
          name: solr
          resources: {}
          volumeMounts:
            - mountPath: /var/solr
              name: solr
      restartPolicy: Always
      volumes:
        - name: solr
          persistentVolumeClaim:
            claimName: solr
status: {}
