apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: solr
  name: solr
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: "{{ .Values.SOLR_PVC_TYPE }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.SOLR_PVC_SIZE }}"
status: {}
