apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    logging: promtail
    logging_jobname: containerlogs
  creationTimestamp: null
  labels:
    phaidra.app: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      phaidra.app: ui
  strategy: {}
  template:
    metadata:
      annotations:
        logging: promtail
        logging_jobname: containerlogs
      creationTimestamp: null
      labels:
        io.kompose.network/phaidra-network: "true"
        phaidra.app: ui
    spec:
      containers:
        - env:
            - name: "OUTSIDE_HTTP_SCHEME"
              value: "{{ .Values.OUTSIDE_HTTP_SCHEME }}"
            - name: "PHAIDRA_HOSTNAME"
              value: "{{ .Values.PHAIDRA_HOSTNAME }}"
            - name: "PHAIDRA_HOSTPORT"
              value: "{{ .Values.PHAIDRA_HOSTPORT }}"
            - name: "PHAIDRA_PORTSTUB"
              value: "{{ .Values.PHAIDRA_PORTSTUB }}"
            - name: "PHAIDRA_PRIMARY_COLOR"
              value: "{{ .Values.PHAIDRA_PRIMARY_COLOR }}"
          image: testuser34/ui-base:latest
          name: ui
          resources: {}
      restartPolicy: Always
status: {}
