apiVersion: 1

providers:
  - name: Default # A uniquely identifiable name for the provider
    folder: Phaidra # The folder where to place the dashboards
    type: file
    options:
      path:
        /mnt/grafana/dashboards
        # <path to dashboard definitions>
        # Default path for Windows: C:/Program Files/GrafanaLabs/grafana/public/dashboards
        # Default path for Linux is: /var/lib/grafana/dashboards
